### ISSUE TITLE
NoMethodError in Messages#new

### ISSUE THREAD

**Issue by Origin10** [CalvertYang/Synergy#1]
不好意思我在運行您的範例時出現這個錯誤，因為小弟是ROR的新手。想請教一下大大該怎麼解決？

NoMethodError in Messages#new

undefined method `id' for nil:NilClass

Extracted source (around line #3):

```
module MessagesHelper'
  def recipients_options(chosen_recipient = nil)
    options_for_select(User.all.map { |user| [user.name, user.id, { 'data-img-src' => gravatar_image_url(user.email, size: 50) }] }, chosen_recipient.id)
  end
end
```

module MessagesHelper
  def recipients_options(chosen_recipient = nil)
    options_for_select(User.all.map { |user| [user.name, user.id, { 'data-img-src' => gravatar_image_url(user.email, size: 50) }] }, chosen_recipient.id)
  end
end

Rails.root: /Users/LinCZ/Synergy

Application Trace | Framework Trace | Full Trace
app/helpers/messages_helper.rb:3:in `recipients_options'
app/views/messages/new.html.erb:16:in`block in _app_views_messages_new_html_erb__179878376275840563_70101333260600'
app/views/messages/new.html.erb:3:in `_app_views_messages_new_html_erb__179878376275840563_70101333260600'
Request

Parameters:

None
Toggle session dump
Toggle env dump
Response

Headers:

None

**Comment by calvertyang** [comment]
先前少判斷了 chosen_recipient 為 nil 的狀況，程式碼已修正
